myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.home,name="home"),
   # path('<int:pk>/delete_view',views.delete_view,name="delete-view"),
   path('update_view',views.update_view,name="update-view"),
   path('delete_view',views.delete_view,name="delete-view"),
   path('people',views.people,name='people'),
   path('add_record',views.add_record,name='add-record'),
   # path('',views.add_record,name="home"),
]

pg_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

myapp/models.py
from django.db import models
#from django.utils import timezone

# Create your models here.

class People(models.Model):
    name = models.CharField(max_length=100)
    birthday = models.DateField(null=True, blank=True)
    #date = models.DateTimeField(default=timezone.now)
    #age = models.IntegerField(max_length=3)
    country = models.CharField(max_length=100)
    organization = models.CharField(max_length=100)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def age(self):
        import datetime
        return int((datetime.date.today() - self.birthday).days / 365.25  )

myapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import People
class RecordForm(forms.Form):
    name = forms.CharField(max_length=100)
    birthday = forms.DateField()
    country = forms.CharField(max_length=100)
    organization = forms.CharField(max_length=100)
    role = forms.CharField(max_length=100)
    id = forms.IntegerField(widget = forms.HiddenInput(), required = False,label='',initial=-1)

class RecordUpdateForm(ModelForm):
    class Meta:
        model = People
        fields = ['name','birthday','country','organization','role']

myapp/views.py
from django.shortcuts import render, redirect
from .models import People
from .forms import RecordForm, RecordUpdateForm
from django.http import JsonResponse,HttpResponse
import json


def home(request):
    
    form = RecordForm()
    template_name="myapp/home.html"
    context={
        'form':form,
        'people':people,
    }
    return render(request, template_name,context)            

def delete_view(request):
    pk=request.POST['pk']
    p = People.objects.get(pk=pk)
    if request.method == 'POST':   
        p.delete()
        #return JsonResponse()
        # return redirect('home')
    # data={
    #     'peoples':list("list"),
    # }
    data={
        'status':'ok',
    }
    return HttpResponse(data)
    # return render(request)

# def update_view(request,pk):
#     people = People.objects.all()

#     p = People.objects.get(pk=pk)
    
#     if request.method == 'POST':
#         u_form = RecordUpdateForm(request.POST,instance=p)
#         if u_form.is_valid():
#             u_form.save()
#             return redirect('home')

#     else:
#         u_form = RecordUpdateForm(instance=p)
    
#     template_name="myapp/home.html"
#     context={
#         'people':people,
#         'u_form':u_form,
#     }
#     return render(request, template_name,context)

def update_view(request):
    pk = request.POST['pk']
    p = People.objects.get(pk=pk)
    
    data = {
        'name':p.name,
        'birthday':str(p.birthday),
        'country':p.country,
       'organization':p.organization,
       'role':p.role,
    }
    
    response = json.dumps(data)
    return HttpResponse(response)

def people(request):
    peoples = People.objects.all()
    
    data={
        'peoples':list(peoples.values()),
    }
    return JsonResponse(data)

def add_record(request):
    # form = RecordForm()
    pk = request.POST['pk']
    if request.method == 'POST':
        name = request.POST['name']
        birthday = request.POST['birthday']
        country = request.POST['country']
        organization = request.POST['organization']
        role = request.POST['role']

        obj, created = People.objects.update_or_create(
            
            pk=pk,
    defaults={'name':name,'birthday':birthday,'country':country,'organization':organization,'role':role},

)
        # p = People(name=name, birthday=birthday, country=country, organization=organization,role=role)
        # p.save()

    data={
        'status':'ok',
    }
    return HttpResponse(data)

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>A DB</title>
</head>
<body>
    <div class="wrapper">
        <header class="main-header">
            <h3>A DB</h3>
        
        </header>
    
        <main class="main">
            {% block content %}
            {% endblock %}
        </main>
    
        <footer>
            <p>Copyright &copy; Lixo LLC</p>
        </footer>
    </div>
    
</body>
</html>

myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}

{% block content %}

    <div class="container">
        <section class="form-section">
            <h3>Add/Update Record</h3>
            <form id="recordForm" method="POST">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        <div class="dj-form">
                           <div class="form-l">
                            {{ field.label_tag }}
                           </div >
                           <div class="form-f">
                            {{ field }}
                           </div>
        
                        </div>
                        
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <!-- <input class="btn-submit" type='submit' value="Submit"> -->

                    <div class="dj-form">
                        
                        <a style="text-decoration: none; text-align: center; color: black;" href="{% url 'home' %}" class="btn">Clear</a>
                        <input id="submit" class="btn" type='submit' value="Submit">
                    </div>
                </fieldset>
            </form>
            
        </section>

        <section class="data-section">
            <h1>Most Influential People in Tech</h1>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Organization</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="people-data">
                    <!-- {% for i in people %}
                    <tr>
                        <td>{{i.name}}</td>
                        <td>{{i.role}}</td>
                        <td>{{i.organization}}</td>
                        <td >
                            <div class="actions">
                                <form action="{% url 'update-view' i.pk %}">
                                
                                    <button class="btn" name="update" type="submit" >Update
                                    </button>
                                </form>
    
                                <form method="POST" action="{% url 'delete-view' i.pk %}">
                                    {% csrf_token %}
                                    <button class="btn danger" type="submit" >Delete
    
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    {% endfor %} -->
                </tbody>
            </table>
        </section>

       <script>
           $(document).ready(function(){
               setInterval(function(){
                   $.ajax({
                       method:'POST',
                       url: "{% url 'people' %}",
                       data : {
                            csrfmiddlewaretoken: '{{csrf_token}}'
                       },
                       success:function(response){
                        //    console.log("Success get data");
                           $("#people-data").empty();
                           for(var i in response.peoples){
                            var temp = `<tr>
                                <td>${response.peoples[i].name}</td>
                                <td>${response.peoples[i].role}</td>
                        <td>${response.peoples[i].organization}</td>
                                <td>
                                    <div class="actions">
                                <form >
                                    {% csrf_token %}
                                    <button id="update" class="btn" name="update" type="button" 
                                    value="${response.peoples[i].id}" >Update
                                    </button>
                                </form>
    
                                <form >
                                    {% csrf_token %}
                                    <button id="delete" class="btn danger" type="button" value="${response.peoples[i].id}">Delete
    
                                    </button>
                                </form>
                            </div>
                            </td>
                            </tr>`;
                            $("#people-data").append(temp);
                      
                          }

                       },
                       error:function(){
                        //    console.log("An Error Occured");

                       },
                   });

               },500);
           });

           $(document).on("submit","#recordForm",function(e){
               e.preventDefault();
               $.ajax({
                   method:"POST",
                   url: "{% url 'add-record' %}",
                   data:{
                        name : $('#id_name').val(),
                        birthday : $('#id_birthday').val(),
                        country : $('#id_country').val(),
                        organization : $('#id_organization').val(),
                        role : $('#id_role').val(),
                        pk : $('#id_id').val(),
                        csrfmiddlewaretoken: '{{ csrf_token}}',

                        
                   },
                   
                  

                success: function(date){
                    // console.log('data successfully send');
                },
                error: function(){
                    console.log("something went wrong");
                },
               });

           });
        //    method for update record

        $(document).on("click","#update",function(e){
                var id = $(this).val();
               e.preventDefault();
               $.ajax({
                    method:"POST",
                    url: "{% url 'update-view' %}",
                    data: {
                        pk :$(this).val(),
                        csrfmiddlewaretoken:'{{csrf_token}}',
                    },
                    success: function(response){
                        var myObj = JSON.parse(response);

                        document.getElementById("id_name").defaultValue = null;
                        document.getElementById("id_birthday").defaultValue = null; 
                        document.getElementById("id_country").defaultValue = null; 
                        document.getElementById("id_organization").defaultValue = null; 
                        document.getElementById("id_role").defaultValue = null; 

                        document.getElementById("id_name").defaultValue = myObj.name;
                        document.getElementById("id_birthday").defaultValue = myObj.birthday; 
                        document.getElementById("id_country").defaultValue = myObj.country; 
                        document.getElementById("id_organization").defaultValue = myObj.organization; 
                        document.getElementById("id_role").defaultValue = myObj.role; 

                        document.getElementById("id_id").defaultValue = id; 

                        console.log(myObj.name);
                console.log("Success update call");
               },
                    error: function(){
                        console.log("error update call");
                    },

               });
               
           });

           // method for delete record

           $(document).on("click","#delete",function(e){
                // var id = document.getElementById('delete').value;
                // var val = $(this).val();
                // console.log(val= "+ val type= "+typeof(val));
               e.preventDefault();
               $.ajax({
                    method:"POST",
                    url: "{% url 'delete-view'  %}",
                    data: {
                        csrfmiddlewaretoken:'{{csrf_token}}',
                        pk :  $(this).val(),
                    },
                    success: function(){
                console.log("success: delete call");
               },
                    error: function(){
                        console.log("error: delete call");
                        
                    },

               });
               
           });
          
       </script>
        
            
       
    </div>
    
    
   

{% endblock %}